modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="analcraft"
version="1.0.0"
displayName="AnalCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="nikita, MCreator"

[[dependencies.analcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



